# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_bt_LmvAmHrgRNAIZ1MoNKSk1EthtnR
"""

"""
Interactive University Registration System
==========================================
Demonstrates: Abstract Classes, Inheritance, Encapsulation, Polymorphism
"""

from abc import ABC, abstractmethod


# ─────────────────────────────────────────────────────────────
# REQUIREMENT 1 — Abstract Base Class (The Blueprint)
# ─────────────────────────────────────────────────────────────

class Course(ABC):
    """
    Abstract blueprint for any university course.
    Cannot be instantiated directly — only subclasses can be used.
    """

    def __init__(self, course_id: str, name: str, credit_hours: int, cost_per_credit: float):
        # REQUIREMENT 3 — Encapsulation: private attributes (name-mangled with __)
        self.__course_id = course_id
        self.__name = name
        self.__credit_hours = credit_hours
        self.__cost_per_credit = cost_per_credit

    # ── Getters ──────────────────────────────────────────────
    @property
    def course_id(self):
        return self.__course_id

    @property
    def name(self):
        return self.__name

    @property
    def credit_hours(self):
        return self.__credit_hours

    @property
    def cost_per_credit(self):
        return self.__cost_per_credit

    # ── Setters with validation (Req 3) ──────────────────────
    @credit_hours.setter
    def credit_hours(self, value: int):
        if not isinstance(value, int) or value < 1 or value > 6:
            raise ValueError("Credit hours must be an integer between 1 and 6.")
        self.__credit_hours = value

    @cost_per_credit.setter
    def cost_per_credit(self, value: float):
        if value <= 0:
            raise ValueError("Cost per credit must be a positive number.")
        self.__cost_per_credit = value

    # ── Abstract methods — subclasses MUST implement these ───
    @abstractmethod
    def calculate_tuition(self) -> float:
        """Calculate total tuition for this course."""
        pass

    @abstractmethod
    def display_course_info(self) -> str:
        """Return a formatted string of course details."""
        pass

    def base_tuition(self) -> float:
        """Shared helper: credit hours × cost per credit."""
        return self.__credit_hours * self.__cost_per_credit


# ─────────────────────────────────────────────────────────────
# REQUIREMENT 2 — Specialization via Inheritance
# ─────────────────────────────────────────────────────────────

class LabCourse(Course):
    """
    Type A — Practical Lab.
    Adds a flat lab equipment fee on top of base tuition.
    """

    EQUIPMENT_FEE = 150.00  # flat fee per semester

    def __init__(self, course_id, name, credit_hours, cost_per_credit, safety_gear_required: bool = False):
        super().__init__(course_id, name, credit_hours, cost_per_credit)
        self.__safety_gear_required = safety_gear_required  # unique property

    @property
    def safety_gear_required(self):
        return self.__safety_gear_required

    # REQUIREMENT 4 — Polymorphism: LabCourse's own version of calculate_tuition
    def calculate_tuition(self) -> float:
        return self.base_tuition() + self.EQUIPMENT_FEE

    def display_course_info(self) -> str:
        gear = "Yes ⚠️" if self.__safety_gear_required else "No"
        return (
            f"  [{self.course_id}] {self.name}\n"
            f"       Type          : Practical Lab 🔬\n"
            f"       Credit Hours  : {self.credit_hours} hrs\n"
            f"       Equipment Fee : ${self.EQUIPMENT_FEE:.2f} (flat)\n"
            f"       Safety Gear   : {gear}\n"
            f"       Est. Tuition  : ${self.calculate_tuition():.2f}"
        )


class LectureCourse(Course):
    """
    Type B — Theoretical Lecture.
    Adds a 5% technology fee on top of base tuition.
    """

    TECH_FEE_RATE = 0.05  # 5% surcharge

    def __init__(self, course_id, name, credit_hours, cost_per_credit,
                 hall_capacity: int = 200, online_link: str = ""):
        super().__init__(course_id, name, credit_hours, cost_per_credit)
        self.__hall_capacity = hall_capacity   # unique property
        self.__online_link = online_link

    @property
    def hall_capacity(self):
        return self.__hall_capacity

    @hall_capacity.setter
    def hall_capacity(self, value: int):
        if value < 1:
            raise ValueError("Hall capacity must be at least 1.")
        self.__hall_capacity = value

    # REQUIREMENT 4 — Polymorphism: LectureCourse's own version of calculate_tuition
    def calculate_tuition(self) -> float:
        base = self.base_tuition()
        return base + base * self.TECH_FEE_RATE

    def display_course_info(self) -> str:
        link_info = self.__online_link if self.__online_link else "In-person only"
        return (
            f"  [{self.course_id}] {self.name}\n"
            f"       Type          : Theoretical Lecture 📖\n"
            f"       Credit Hours  : {self.credit_hours} hrs\n"
            f"       Tech Fee      : {int(self.TECH_FEE_RATE * 100)}% surcharge\n"
            f"       Hall Capacity : {self.__hall_capacity} seats\n"
            f"       Online Link   : {link_info}\n"
            f"       Est. Tuition  : ${self.calculate_tuition():.2f}"
        )


# ─────────────────────────────────────────────────────────────
# REQUIREMENT 4 — StudentSchedule with polymorphic billing
# ─────────────────────────────────────────────────────────────

class StudentSchedule:
    def __init__(self, student_name: str):
        self.__student_name = student_name
        self.__courses: list[Course] = []

    @property
    def student_name(self):
        return self.__student_name

    def add_course(self, course: Course) -> bool:
        for c in self.__courses:
            if c.course_id == course.course_id:
                return False
        self.__courses.append(course)
        return True

    def remove_course(self, course_id: str) -> bool:
        for c in self.__courses:
            if c.course_id == course_id:
                self.__courses.remove(c)
                return True
        return False

    def is_empty(self) -> bool:
        return len(self.__courses) == 0

    def print_schedule(self):
        if self.is_empty():
            print("  ⚠️  Your schedule is empty.")
            return
        print(f"\n  Registered courses for {self.__student_name}:")
        for i, course in enumerate(self.__courses, 1):
            print(f"\n  {i}. {course.display_course_info()}")

    def print_tuition_bill(self):
        if self.is_empty():
            print("  ⚠️  No courses registered. Nothing to bill.")
            return

        W = 58
        print("\n" + "=" * W)
        print("       🎓  UNIVERSITY TUITION BILL")
        print("=" * W)
        print(f"  Student : {self.__student_name}")
        print("-" * W)
        print(f"  {'Course':<30} {'Type':<10} {'Tuition':>10}")
        print("-" * W)

        total = 0.0
        for course in self.__courses:
            tuition = course.calculate_tuition()   # ← polymorphic call
            total += tuition
            kind = "Lab" if isinstance(course, LabCourse) else "Lecture"
            print(f"  {course.name:<30} {kind:<10} ${tuition:>9.2f}")

        print("-" * W)
        print(f"  {'TOTAL SEMESTER FEES':<40} ${total:>9.2f}")
        print("=" * W)
        print("  Thank you for registering. Good luck this semester! 🌟")
        print("=" * W + "\n")


# ─────────────────────────────────────────────────────────────
# Course Catalogue
# ─────────────────────────────────────────────────────────────

def build_catalogue() -> dict:
    courses = [
        LectureCourse("CS101",   "Introduction to Computer Science", 3, 50.0, hall_capacity=150),
        LectureCourse("MATH201", "Linear Algebra",                   3, 45.0, hall_capacity=120),
        LectureCourse("PHYS101", "Physics I",                        3, 48.0, hall_capacity=200,
                      online_link="https://meet.university.edu/phys101"),
        LectureCourse("AI301",   "Artificial Intelligence",          3, 60.0, hall_capacity=100,
                      online_link="https://meet.university.edu/ai301"),
        LectureCourse("ARCH201", "Computer Architecture",            3, 55.0, hall_capacity=80),
        LectureCourse("SIG301",  "Signals & Systems",                3, 52.0, hall_capacity=90),
        LabCourse("CS101L",   "Computer Science Lab",  1, 40.0, safety_gear_required=False),
        LabCourse("PHYS101L", "Physics Lab",           1, 40.0, safety_gear_required=True),
        LabCourse("CHEM101L", "Chemistry Lab",         1, 38.0, safety_gear_required=True),
        LabCourse("NET201L",  "Networking Lab",        2, 45.0, safety_gear_required=False),
    ]
    return {c.course_id: c for c in courses}


# ─────────────────────────────────────────────────────────────
# REQUIREMENT 5 — Terminal Interaction / Main Loop
# ─────────────────────────────────────────────────────────────

def print_banner():
    print("\n" + "=" * 58)
    print("   🎓  INTERACTIVE UNIVERSITY REGISTRATION SYSTEM")
    print("=" * 58)

def print_menu():
    print("\n┌─────────────────────────────────┐")
    print("│          STUDENT PORTAL          │")
    print("├─────────────────────────────────┤")
    print("│  [1]  View Available Courses     │")
    print("│  [2]  Register for a Course      │")
    print("│  [3]  View My Schedule           │")
    print("│  [4]  Drop a Course              │")
    print("│  [5]  Print Tuition Bill         │")
    print("│  [0]  Exit                       │")
    print("└─────────────────────────────────┘")

def view_catalogue(catalogue: dict):
    print("\n" + "─" * 58)
    print("  📋  AVAILABLE COURSES THIS SEMESTER")
    print("─" * 58)
    print("\n  ── Theoretical Lectures ──")
    for course in catalogue.values():
        if isinstance(course, LectureCourse):
            print(f"\n{course.display_course_info()}")
    print("\n  ── Practical Labs ──")
    for course in catalogue.values():
        if isinstance(course, LabCourse):
            print(f"\n{course.display_course_info()}")
    print("─" * 58)

def register_course(catalogue: dict, schedule: StudentSchedule):
    course_id = input("\n  Enter Course ID to register (e.g. CS101): ").strip().upper()
    if course_id not in catalogue:
        print(f"  ❌  Course '{course_id}' not found. Check the catalogue.")
        return
    if schedule.add_course(catalogue[course_id]):
        print(f"  ✅  '{catalogue[course_id].name}' added to your schedule.")
    else:
        print(f"  ⚠️  You are already registered for '{catalogue[course_id].name}'.")

def drop_course(schedule: StudentSchedule):
    if schedule.is_empty():
        print("  ⚠️  Your schedule is empty — nothing to drop.")
        return
    course_id = input("\n  Enter Course ID to drop: ").strip().upper()
    if schedule.remove_course(course_id):
        print(f"  ✅  Course '{course_id}' removed from your schedule.")
    else:
        print(f"  ❌  Course '{course_id}' is not in your schedule.")

def main():
    print_banner()
    student_name = input("\n  Welcome! Please enter your name: ").strip() or "Student"
    schedule = StudentSchedule(student_name)
    catalogue = build_catalogue()
    print(f"\n  Hello, {student_name}! Use the menu below to manage your registration.")

    while True:
        print_menu()
        choice = input("\n  Select an option: ").strip()

        if choice == "1":
            view_catalogue(catalogue)
        elif choice == "2":
            register_course(catalogue, schedule)
        elif choice == "3":
            schedule.print_schedule()
        elif choice == "4":
            drop_course(schedule)
        elif choice == "5":
            schedule.print_tuition_bill()
        elif choice == "0":
            print(f"\n  👋  Goodbye, {student_name}! See you next semester.\n")
            break
        else:
            print("  ❌  Invalid choice. Please enter a number from 0 to 5.")

if __name__ == "__main__":
    main()